version: '3.9'

services:
  catalog_postgres_server:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_PASSWORD=catalog_db_password
      - POSTGRES_USER=catalog_db
    volumes:
      - ./db-data/catalog_postgres_server/:/var/lib/postgresql/data

  order_postgres_server:
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_PASSWORD=order_db_password
      - POSTGRES_USER=order_db
    volumes:
      - ./db-data/order_postgres_server/:/var/lib/postgresql/data

  user_postgres_server:
    image: postgres:14.1-alpine
    ports:
      - "5434:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_USER=user_db
    volumes:
      - ./db-data/user_postgres_server/:/var/lib/postgresql/data