version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_PASSWORD=catalog_db_password
      - POSTGRES_USER=catalog_db
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data